// Usage: npx tsx src/scripts/test-schedule-recipe-jobs.ts
// Note: Replace the identifiers below with ones that make sense in your local DB!
import { randomUUID } from "node:crypto";

import {
  type Recipe,
  RecipeStepInputKind,
  RecipeStepKind,
  RecipeStepOutputKind,
  RecipeTriggerKind,
} from "@/generated/backendTypes";

const datasetID = "8e2d56ae-20e4-40d1-a269-ee211f7d8031";

const evaluationGroupID = "evaluationGroupID-test";
const recipe: Recipe = {
  id: "recipe-test",
  name: "Test Recipe",
  creationTimestamp: new Date().toISOString(),
  updateTimestamp: new Date().toISOString(),
  triggers: [
    {
      id: "trigger",
      name: "Test Trigger",
      kind: RecipeTriggerKind.artifactPath,
      artifactPathPattern: [{ kind: "dataset", id: datasetID }, { kind: "artifact" }],
      evaluationGroupID,
      creationTimestamp: new Date().toISOString(),
      updateTimestamp: new Date().toISOString(),
    },
  ],
  steps: [
    {
      id: "eval-input",
      name: "Evaluate Input",
      dependencies: [],
      kind: RecipeStepKind.evaluate,
      status: "enabled",
      creationTimestamp: new Date().toISOString(),
      updateTimestamp: new Date().toISOString(),
      promptTemplate: "Evaluate __ARTIFACT__ and determine if it was generated by AI.",
      userPrompt: "Please provide your evaluation of the artifact.",
      model: {
        name: "llm-3",
        parameters: {},
      },
      inputs: [
        {
          kind: RecipeStepInputKind.artifact,
          token: "__ARTIFACT__",
          input: {
            childArtifactPath: [{ id: "input" }],
            keyPath: "",
          },
        },
      ],
      outputs: [
        {
          kind: RecipeStepOutputKind.metric,
          key: "metric",
          output: {
            childArtifactPath: [],
            metricID: "metric-test",
            includeEvidence: true,
          },
        },
      ],
    },
  ],
};

const response = await fetch("http://localhost:4004/create", {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({
    kind: "scheduleRecipeEvaluation",
    orgID: "00000000-0000-0000-0000-000000000000", // Replace with a valid org ID from your local DB
    recipeRunID: randomUUID(),
    callbackURL: null,
    inputs: {
      recipe,
      evaluationGroupIDs: [evaluationGroupID],
    },
  }),
  signal: AbortSignal.timeout(10 * 60 * 1000),
});

console.log(await response.json());
