name: Frontend unit test
description: Run frontend unit tests.

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: frontend/.nvmrc
        cache: npm
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      shell: bash
      working-directory: frontend
      run: npm ci

    - name: Install Playwright Browsers
      shell: bash
      working-directory: frontend
      run: npx --no playwright install --with-deps --only-shell

    - name: Run tests
      shell: bash
      working-directory: frontend
      run: npm run test:unit
