name: lumiflow-ai
services:
  database:
    image: postgres:12.20-bullseye
    container_name: postgres
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    command: ["postgres", "-c", "log_statement=all"]
volumes:
  database-data:
