name: Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/backend.yml
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/backend.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run backend build
        uses: ./backend/.github/actions/build

  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run backend lint
        uses: ./backend/.github/actions/lint

  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run backend tests
        uses: ./backend/.github/actions/test
